# 문자열

## 문자열 생성방법 -1

In [16]:
"Life is too short, you need python."

'Life is too short, you need python.'

In [17]:
#1. 큰 따옴표
"Hello world"

'Hello world'

In [18]:
#2. 작은 따옴표
'python is interesting'

'python is interesting'

In [19]:
#3. 큰 따옴표 3개를 넣는 방법
"""Life is too short, you need python."""

'Life is too short, you need python.'

In [20]:
#4. 작음 따옴표 3개를 넣는방법
'''Life is too short, you need python.'''

'Life is too short, you need python.'

## Multi-line을 만들고자 할 떄

In [21]:
# 1.\n (Escape Code)
multi = "Life is too short,\nyou need python."
print(multi)

Life is too short,
you need python.


In [22]:
# 2. 작은 따옴표 3개

multi2 = '''Life is to short,
you need python.'''
print(multi2)
# 3. 큰 따옴표 3개

multi3 = """Life is to short,
you need python."""
print(multi3)

Life is to short,
you need python.
Life is to short,
you need python.


## concatenation :: 덧셈

In [24]:
head = 'you need'
tail = ' python'
head + tail

'you need python'

In [32]:
a = [1,2,3]
b = [4,5,6]

a+b

[1, 2, 3, 4, 5, 6]

In [35]:
import numpy as np # 별칭(aliase)

a_1 = np.array(a)
b_1 = np.array(b)

print(a_1 + b_1)

c= [a+b for a,b in zip(a,b)]
print(c)

[5 7 9]
[5, 7, 9]


In [37]:
## 문자열의 곱하기
b = 'python '
answer = b*2
print(answer)


python python 


In [38]:
# 문자열 곱하기
print('-'*30)
print('test')
print('-'*30)

------------------------------
test
------------------------------


In [40]:
# 문자열의 길이 구하기
x = 'Life is too short, you nedd python'
len(x)

34

## 문자열 인덱싱과 슬라이싱

In [42]:
x[-1]

'n'

In [45]:
# 슬라이싱으로 문자열 나누기
date = '20220525sunny'
year = date[0:4]
day = date[4:8]
weather = date[8:]
print(year)
print(day)
print(weather)

2022
0525
sunny


In [47]:
# 참고사항
a = 'pithon'
a[1]
result=a[:1]+'y'+a[2:]
print(result)

python


# 문자열 포매팅

In [50]:
"현재온도는 26도 입니다."
"현재온도는 16도 입니다."

'현재온도는 16도 입니다.'

## % 연산자를 통한 숫자 바로 대입

In [51]:
# 숫자를 바로 대입하는 방법
"현재 온도는 %d도 입니다" % 26 #decimal 십진수

'현재온도는 26도 입니다'

In [ ]:
# 문자를 바로 대입하는 방법
"현재 온도는 %s도 입니다" % '이십 육' #s 는 str

In [52]:
# 숫자 값을 변수로 대입 하여서 적용
num = 3
"I eat %d pythons" % num

'I eat 3 pythons'

In [55]:
# 2개 이상의 값을 넣기

num = 10
day = 'five'

"I ate %d pythons so i was sick for %s days" % (num, day)

'I ate 10 pythons so i was sick for five days'

In [ ]:
## 문자열 포맷 코드

In [56]:
## 참고사항 %%
"Accuracy is %d%%" %95

'Accuracy is 95%'

# 포맷코드와 숫자를 통한 정렬

In [61]:
# 1. 정렬과 공백
"%10s" % 'bigdata' # 오른쪽 정렬
"%-10s" % 'bigdata' # 왼쪽 정렬

'bigdata   '

In [69]:
# 2. 소수점 표현하기
'%20.12f' % 3.141592212343545

'      3.141592212344'

## format 함수를 활용한 포매팅

In [70]:
# 숫자 바로 대입하기
"I eat {0} pythons".format(3)

'I eat 3 pythons'

In [71]:
# 문자열 바로 대입하기
"I eat {0} pythons".format('five')

'I eat five pythons'

In [72]:
# 숫자 값을 가진 변수로 대입하기
num1 = 3
"I eat {0} pythons".format(num1)

'I eat 3 pythons'

In [74]:
# 숫자 값을 가진 변수로 대입하기
num1 = 3
day1 = 'six'


"I eat {0} pythons so i was sick for {1} days".format(num1, day1)

'I eat 3 pythons so i was sick for six days'

In [77]:
import numpy as np
array1 = np.arange(1, 11)
print(array1)
array1.reshape(10, 1)

[ 1  2  3  4  5  6  7  8  9 10]


array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [82]:
# format 함수를 통한 정렬
# 왼쪽정렬
'{0:<10}'.format('hi')
'{0:>10}'.format('hi')
'{0:^10}'.format('hi')

'    hi    '

In [85]:
# 왼쪽정렬
'{0:?<15}'.format('님 나 아심')
# 왼쪽정렬
'{0:?>15}'.format('hi')

'?????????????hi'

In [88]:
## 포맷 함수를 통한 소수점 표현
y = 3.141592123456780
'{0:.4f}'.format(y) # 원칙{0:0.4f}
'{0:.4f}'.format(y) # 실무{0:.4f}

# 오른쪽 정렬을 통한 formatting
'{0:10.4f}'.format(y)

'    3.1416'

# f 문자열 포매팅

파이썬 3.6버전부터는 f문자열 포매팅 기능을 사용할 수 있다. (3.6미만 버전에서 사용불가능)

In [90]:
name = 'dyh'
age = 31

# format 함수를 통해 활용
'제 이름은 {name}입니다. 나이는 {age}입니다.'.format(name='dyh', age=31)
# f 포매팅을 통해 활용
f'제 이름은 {name}입니다. 나이는 {age}입니다'

'제 이름은 dyh입니다. 나이는 31입니다'

In [92]:
# f 포매팅 변칙
age = 29
f'나는 내년이면 { age+1 }살이 됩니다'

'나는 내년이면 30살이 됩니다'

In [99]:
# f 포매팅을 dict로 표현해보기
dict1 = {'name':'dyh', 'age':30}
f'제이름은 {dict1["name"]} 이고 나이는 {dict1["age"]} 입니다.'

'제이름은 dyh 이고 나이는 30 입니다.'

In [103]:
# 정렬의 방식
f'{"hi":<10}' #왼쪽정렬
f'{"hi":>10}' #오른쪽정렬
f'{"hi":^10}' #중앙정렬


'    hi    '

In [104]:
# 정렬의 방식
f'{"hi":!<10}' #왼쪽정렬
f'{"hi":!>10}' #오른쪽정렬
f'{"hi":!^10}' #중앙정렬

'!!!!hi!!!!'

# 문자열 관련함수 우선순위1

In [116]:
### Split 함수 -1

a = "Life is too short" # 한 덩어리의 str
a.split()

['Life', 'is', 'too', 'short']

In [117]:
### Split 함수 -2

b = 'a!b!c!d'
b.split('!')

['a', 'b', 'c', 'd']

In [118]:
# replace 함수

a = 'Life is too short'
a.replace('Life', 'My height')

'My height is too short'

In [119]:
# join 함수

test = "abcd"
','.join(test)

'a,b,c,d'

### 문자열 관련함수 우선순위2

In [120]:
# 문자 개수 세기(count)

a = 'happy'
a.count('p')

2

In [123]:
# 위치 알려주기1 (find)

a = 'Big Data is the best choice'
a.find('b')
a.find('l')

-1

In [126]:
# 위치 알려주기2 (index)

a = 'Big Data is the best choice'
a.index('b')
a.index('l')

ValueError: substring not found

### 문자열 관련함수 우선순위3

In [128]:
# 소문자 -> 대문자
a = 'Hello'
a.upper()

'HELLO'

In [129]:
# 대문자 -> 소문자
a = 'HI'
a.lower()

'hi'

In [130]:
# end of file